VisthusetAPI/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from VisthusetAPI.views import *
import database.views as booking


urlpatterns = [
    # Visthuset urls
    url(r'^$', IndexView, name="visthuset_index"),
    url(r'^meny/$', meny_view, name="meny"),
    url(r'^calendar/$', CalendarView.as_view(), name="calendar"),
    url(r'^events/', include('events.urls')),
    url(r'^about/$', about_view, name="about"),
    url(r'^contact/$', contact_view, name="contact"),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^uthyrning/$', UthyrningView.as_view(), name="uthyrning"),
    
    # API urls
    url(r'^api/$', APIIndexView.as_view(), name="api_index"),
    url(r'^admin/', admin.site.urls),
    url(r'^cleaning/', include('cleaning.urls')),
    url(r'^economy/', include('Economy.urls')),
    url(r'^booking/', include('database.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^admin/availablebike/$', booking.create_available_bikes, name='createbikes'),
]

database/urls.py
'''
Created on 16 okt. 2016

@author: Adrian
'''
from django.conf.urls import url
from . import views, calendars

app_name = "database"
urlpatterns = [
    # /bookings/
    url(r'^availablebike/$', views.create_available_bikes, name='createbikes'),
    url(r'^bookingcal/$', views.booking_calendar, name='bookingcalendar'),
    url(r'^viewbookings/$', views.view_bookings, name='bookings_today'),
    # /bookings/bookingNo/
    url(r'^calendar/$', calendars.calendar, name='eventcalendar'),
    url(r'^bikebooking/', views.customer_bike_booking_view, name='bike_booking'),
    url(r'^package/$', views.package_display, name='package_list'),
    url(r'^package/(?P<slug>[a-z]+)/', views.package_booking, name='package'),
    url(r'^(?P<pk>[0-9]+)/thanks/$', views.confirmation_view, name='confirmation'),
    #url(r'^(?P<booking>[0-9]+)/$', views.ViewBooking.as_view(), name='booking-detail')
    ]
#views.BikeBookingResponseView.as_view()    ]

docs/urls.py
'''
Created on 16 okt. 2016

@author: Adrian
'''
from django.conf.urls import url
from . import views

app_name = 'docs'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'Index'),
    url(r'^tutor/', views.tutor, name='Tutor'),
]

database/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse
from .forms import CreateAvailableBikeForm, ChildBikeBookingForm, ChildBikeFormset
from datetime import datetime, timedelta, date
from django.forms.formsets import formset_factory
from database.forms import BaseCreateAvailableBikeFormset, CustomerBikeBookingForm,\
    CustomerPackageBookingForm
from django.contrib.admin.views.decorators import staff_member_required
from database.models import *
from django.utils.safestring import mark_safe
from database.calendars import BikeCalendar, BookingsCalendar
from database.helperfunctions import create_date_list
from docs.models import EmailTexts
from django.core.mail import send_mail
from django.template import Template, Context
from docs.models import Page, PageContent
from django.views.generic.detail import DetailView

def perdelta(start, end, delta):
    curr = start
    while curr <= end:
        yield curr
        curr += delta

@staff_member_required
def create_available_bikes(request):
    # Formset for creating bikes
    CreateAvailableBikeFormset = formset_factory(CreateAvailableBikeForm,
                                                 formset=BaseCreateAvailableBikeFormset,
                                                 extra=1,
                                                 max_num=25,
                                                 )
    if request.method == 'POST':
        formset = CreateAvailableBikeFormset(request.POST, request.FILES)
        if formset.is_valid():
            for form in formset:
                data = form.cleaned_data
                start = data['from_date']
                numdays = data['to_date'].day - start.day
                date_list = [(start + timedelta(days=x)) for x in range(0,numdays + 1)]
                
                if data['bike'] is not None:
                    # Create available bike
                    if data['action'] == 'create':
                        for day in date_list:
                            BikeAvailable.objects.get_or_create(
                                    bike = data['bike'],
                                    available_date = day)

                    # Delete available bike
                    elif data['action'] == 'delete':
                        bk = BikeAvailable.objects.filter(
                                bike = data['bike'],
                                available_date__gte = start).filter(
                                    bike = data['bike'],
                                available_date__lte = data['to_date'])
                        bk.delete()
                else:
                    if data['action'] == 'all':
                        print('all')
                        for bike in Bike.objects.all():
                            for day in date_list:
                                BikeAvailable.objects.get_or_create(
                                        bike=bike,
                                        available_date = day)
    else:
        formset = CreateAvailableBikeFormset()
        
    # Calendar
    today = datetime.now()
    my_bikes = BikeAvailable.objects.all().order_by('available_date')
    calendar = BikeCalendar(my_bikes).formatmonth(today.year, today.month)
    '''
    TODO:
    # Make sure no two same available bikes can be created. For instance via unique together
    # create calendar for bikes
    '''
    
    return render(request, 'bookings/create_available_bikes.html',
                  {'formset': formset,
                   'calendar': mark_safe(calendar),
                   })

def customer_bike_booking_view(request):
    # Get page text data from database
    pagename = 'uthyrning'
    page = Page.objects.get(code=pagename)
    texts = PageContent.objects.filter(page__code = pagename, publish=True).order_by('order')
    
    # Form data and handling
    if request.method == 'POST':
        form = CustomerBikeBookingForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            # Time variables
            start_date = data['start_date']
            duration = data['duration']
            end_date = start_date + duration - timedelta(days=1)
            date_list = create_date_list(start_date, duration.days)
            
            # Build bike dictionary
            bikes = {'adult': data['adult_bikes'], 'young': data['young_bikes'], 
                     'child': data['child_bikes'], 'smallChild': data['small_child_bikes']}
            
            # Count number of bikes
            number_of_adults = data['adult_bikes']
            number_of_children = (int(data['small_child_bikes']) + int(data['child_bikes']) + 
                                  int(data['young_bikes']))
            # Messages
            biketype_dict = {'adult': 'vuxencykel', 'young': 'ungdomscykel', 'child': 'barncykel',
                    'smallChild': 'småbarncykel'}
            
            bike_list = []
            for biketype, amount in bikes.items():
                if amount is not None and amount > 0:
                    success, list = (BikeAvailable.objects.
                                            get_available_bikes_for_dates(biketype,
                                                                          amount,
                                                                          start_date,
                                                                          end_date,
                                                                          duration))
                    if success:
                        bike_list += list
                    else:
                        return render(request, 'bookings/bike_booking.html', {'form': form,
                                                                              'page': page,
                                                                              'texts': texts,
                                                                              'message': mark_safe('''
                                         Det verkar som att vi inte har tillräckligt många {} lediga<br>
                                         för en eller flera av de önskade dagarna. Ring oss gärna på<br>
                                         0506 - 77 75 50 eller skicka ett mejl till <a href="mailto:info@cafevisthuset.se">
                                         info@cafevisthuset.se</a> så kanske vi kan hjälpa till.
                                         '''.format(biketype_dict[biketype]))})
            # Get or create guest
            guest = GuestProfile.objects.post_get_or_create(data['first_name'],
                                                     data['last_name'],
                                                     data['email'],
                                                     kwargs={'phone_number': data['phone_number'],
                                                             'newsletter': data['newsletter']})
            # Create booking
            booking = Booking.objects.create(guest=guest,
                                          start_date=start_date,
                                          end_date=end_date,
                                          adults=number_of_adults,
                                          children=number_of_children,
                                          status='actv',
                                          special_requests=data['other'])
            # Book bikes
            # bike booking not used, but can be used for debugging
            success, bike_booking = booking.setBikeBooking(bike_list, start_date, end_date, duration)
            
            # Should not happen
            if not success:
                '''
                TODO:
                # Implement report if something goes wrong and send an email to us. 
                '''
                return render(request, 'failed.html')
            '''
            TODO:
            # Implement booking of bike extras to 
            '''
            # Build lunch dictionary
            lunches ={'veg': data['veg_lunch'], 'fish': data['fish_lunch'], 'meat': data['meat_lunch']}
            # Book lunches
            for lunchtype, amount in lunches.items():
                if amount > 0:
                    LunchBooking.objects.create(
                            type=Lunch.objects.get(slug=lunchtype), 
                            day=start_date,
                            quantity=amount,
                            booking=booking)
            
            # Saves the booking and updates prices
            booking.save()
            return redirect('database:confirmation', pk = booking.booking)
            
    else:
        form = CustomerBikeBookingForm()
        
    return render(request, 'bookings/bike_booking.html', {'form': form, 'page':page, 'texts':texts})  

@staff_member_required
def booking_calendar(request):
    today = datetime.today()
    bookings = BikeAvailable.objects.all().order_by('available_date').exclude(bookings=None)
    calendar = BookingsCalendar(bookings).formatmonth(year=today.year, month=today.month)
    return render(request, 'bookings/viewfreebikes.html', {'calendar': mark_safe(calendar),})

@staff_member_required
class ViewBooking(DetailView):
    template_name = 'bookings/bookingdetail.html'
    model = Booking
    context_object_name = 'booking'

@staff_member_required
def view_bookings(request):
    today = Booking.objects.filter(start_date=date.today()).exclude(status='cancl')
    tomorrow = Booking.objects.filter(start_date=date.today()+timedelta(days=1)).exclude(status='cancl')
    day_after_tomorrow = Booking.objects.filter(start_date=date.today()+timedelta(days=2)).exclude(status='cancl')
    return render(request, 'bookings/viewbookings.html', {'today': today,
                                                          'tomorrow': tomorrow,

database/templates/bookings/bike_booking.html
{% extends '../visthuset_base.html' %}

{% load rest_framework %}

{% block title %}<title>{{ page.title }}</title>{% endblock %}

{% block content %}

<section class="row">
	<div class="col-xs-11 col-md-7 col-offset-1 mt-0" >
		<div class="text-info mt-0">
			<h1 class="mt-0">{{ page.headline }}</h1>
			{{ page.ingress | safe }}
		</div>
		{% for text in texts %}
		<div class="text-info ">
			<h2>{{ text.headline }}</h2>
			{% if text.image %}
			<img class="img-responsive col-s-12 col-md-3" src="/{{ text.image }}" alt="{{ text.image_alt }}">
			{% endif %}
			<p>{{ text.text | safe }}</p>
		</div>
		<div class="embed-responsive embed-responsive-16by9">
			<iframe class="embed-responsive-item" src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Fcafevisthuset%2Fvideos%2F1296951783686704%2F&show_text=0&width=560" width="560" height="315" style="border:none;overflow:hidden" scrolling="no" allowTransparency="true" allowFullScreen="true"></iframe>
		</div>
	</div>
	{% endfor %}

	<div class="col-xs-11 col-md-4 col-offset-2 panel " style="padding-bottom: 5%;">
		<p class="text-danger">{{ message }}</p>
		<div class="panel-heading">
		<h3 class="text-primary">Boka cykel här!</h3>
		</div>
		<form class="form-group panel-body" action="" method="post" >
			{% csrf_token %}
			{% for field in form %}
			{% if form.errors %}
		        <p class="text-danger">{{ field.errors }}</p>
		    {% endif %}
		        <label class="col-form-label" style="display:block;" for="{{ field.name }}">{{ field.label }}</label>
		        {{ field }}
		        {% if field.help_text %}
		        <small class="form-text text-muted">{{ field.help_text|safe }}</small>
		        {% endif %}
		    	
			{% endfor %}
			<br>
			<input type="submit" class="btn btn-primary btn-block pull-right" value="Boka!"/>
		</form>
	</div>
	</div>
</section>
{% endblock %}
{% render_form serializer template_pack='rest_framework/vertical' %}

database/templates/bookings/bookingdetail.html
{% extends "admin/app_index.html" %}
{% load i18n admin_modify %}
{% block extrahead %}{{ block.super }}
{% url jsi18n as jsi18nurl %}
<script src="{{ jsi18nurl}}" type="text/javascript"><!--mce:0--></script>  
{% endblock %}
{% block extrastyle %}{{ block.super }}
{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">  
     <a href="../../admin/">{% trans "Home" %}</a> ›
     {% trans 'Se enskild bokning' %}</div>
{% endif %}{% endblock %}

{% block content %}

	{{ booking }}

{% endblock %}

database/templates/bookings/change_form.html
{% extends "./admin/change_form.html" %}
{% load i18n admin_urls %}
{% block object-tools %}
{% if change %}{% if not is_popup %}
<ul class="object-tools">  
    {% url opts|admin_urlname:'review' original.pk|admin_urlquote as review_url %}
    <li><a href="{% add_preserved_filters review_url %}" class="historylink">{% trans "Review" %}</a></li>

    {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
    <li><a href="{% add_preserved_filters history_url %}" class="historylink">{% trans "History" %}</a></li>

    {% if has_absolute_url %}<li><a href="{{ absolute_url }}" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif %}
</ul>  
{% endif %}{% endif %}
{% endblock %}

database/templates/bookings/confirmation.html
{% extends "../visthuset_base.html" %}
{% block title %}<title>{{ page.title }}</title>{% endblock %} 

{% block content %}
<section class="row">
	<div class="col-sm-12 col-md-6">
	<h1 class="text-info">{{ headline }}</h1>
	<p>{{ ingress }}</p>
	<p>{{ confirmation }}</p>
	</div>
	{% if texts %}
	<div class="col-sm-12 col-md-6">
		{% for text in texts %}
			<h3 class="text-info">{{ text.headline }}</h3>
			<p>{{ text.text | safe }}</p>
		{% endfor %}
	</div>
	{% endif %}
	{% if texts.image %}
	<div class="img-responsive">
		<img src="{{ texts.image }}">
	</div>
	{% endif %}
	{% if included_bikes.keys is not None %}
	<div>
		<h3 class="text-info">Cyklar</h3>
		<p>
		{% for key, value in included_bikes.items %}
			{{ value }} st {{ key }}<br>
		{% endfor %}
		</p>
	</div>
	{% endif %}
	
	{% if included_lunches %}
	<div class="text-info">
		<h3>Luncher</h3>
		<p>
		{% for key, value in included_lunches.items %}
			{{ value }} {{ key }}<br>
		{% endfor %}
		</p>
	</div>
	{% endif %}

</section>
{% endblock content %}

database/templates/bookings/create_available_bikes.html
{% extends "admin/app_index.html" %}
{% load i18n admin_modify %}
{% block extrahead %}{{ block.super }}
{% url jsi18n as jsi18nurl %}
<script src="{{ jsi18nurl}}" type="text/javascript"><!--mce:0--></script>  
{% endblock %}
{% block extrastyle %}{{ block.super }}
{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">  
     <a href="../../admin/">{% trans "Home" %}</a> ›
     {% trans 'Skapa tillgänglighet för cyklar' %}</div>
{% endif %}{% endblock %}

{% block content %}

	{{ calendar }}


<form method="post" action="">
	{% csrf_token %}
	<div class="form-row">
	<table>
		
		{{ formset }}
		
	</table></div>
	<input type="submit" value="Lägg till tillgänglighet"/>
</form>
{% endblock %}

database/templates/bookings/package.html
{% extends '../visthuset_base.html' %}
{% load static %}
{% block title %}<title>Boka {{ package.title }}</title>{% endblock %}

{% block content %}
<section class="row">
	<div class="col-xs-12 col-md-6">
		<img alt="{{ package.image_alt}}" src="{{ package.image.url }}" class="image-responsive">
		<h1 class="heading text-info">Boka {{ package.title }}!</h1>
		<p class='text-primary'>{{ package.ingress }}</p>
		{% for day in days %}
		<h3 class="heading text-info mt-0"><u>Dag {{day.order}}, avstånd: {{ day.distance }} km, slussar: {{ day.locks }}</u></h3>
		<p>{{ day.text }}</p>
		{% endfor %}
	</div>
	<div class="col-xs-11 col-md-4 col-offset-2 panel " style="padding-bottom: 5%;">
		<p class="text-danger">{{ message }}</p>
		<div class="panel-heading">
		<h3 class="text-primary">Boka paketet här!</h3>
		</div>
		<form class="form-group panel-body" action="" method="post" >
			{% csrf_token %}
			{% for field in form %}
			{% if form.errors %}
		        <p class="text-danger">{{ field.errors }}</p>
		    {% endif %}
		        <label class="col-form-label" style="display:block;" for="{{ field.name }}">{{ field.label }}</label>
		        {{ field }}
		        {% if field.help_text %}
		        <small class="form-text text-muted">{{ field.help_text|safe }}</small>
		        {% endif %}
		    	
			{% endfor %}
			<br>
			<input type="submit" class="btn btn-primary btn-block pull-right" value="Skicka bokningsförfrågan!"/>
		</form>
	</div>
</section>
{% endblock content %}

database/templates/bookings/package_booking.html
{% extends '../visthuset_base.html' %}

{% block title %}<title>{{ page.title }}</title>{% endblock %}

{% block content %}
<section class="row">
	<div class="col-xs-11 col-md-11 col-offset-1 centered" >
		<h1>{{ page.headline }}</h1>
		{{ page.ingress | safe }}
	</div>
	{% for package in packages %}
	<div class="col-s-12 col-md-5">
		<h2>{{ package.text.name }}</h2>
		{% if package.image %}
		<img class="img-responsive col-s-12 col-md-3" src="/{{ package.image }}" alt="{{ package.image_alt }}">
		{% endif %}
		{% for day in package.days %}
		<p>{{ day.text | safe }}</p>
		{% endfor %}
	</div>
	{% endfor %}
</section>
{% endblock %}

database/templates/bookings/packagedisplay.html
{% extends '../visthuset_base.html' %}

{% block title %}<title>{{ page.title }}</title>{% endblock %}

{% block content %}
<section class="row">
	<div class="col-xs-11 col-md-11 col-offset-1 centered" >
		<h1>{{ page.headline }}</h1>
		{{ page.ingress | safe }}
	</div>
	{% for package in packages %}
	<div class="col-s-12 col-md-6">
		<h2 class='text-info'>{{ package.title }}</h2>
		<img class="img-responsive" src="{{ package.image }}" alt="{{ package.image_alt }}">
		<a href="{% url 'database:package' package.slug %}" class='btn btn-primary'>Läs mer och boka!</a>
	</div>
	{% endfor %}
</section>
{% endblock %}

database/templates/bookings/viewbookings.html
{% extends "admin/app_index.html" %}
{% load i18n admin_modify %}
{% block extrahead %}{{ block.super }}
{% url jsi18n as jsi18nurl %}
<script src="{{ jsi18nurl}}" type="text/javascript"><!--mce:0--></script>  
{% endblock %}
{% block extrastyle %}{{ block.super }}
{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">  
     <a href="../../admin/">{% trans "Home" %}</a> ›
     {% trans 'Se alla bokningar' %}</div>
{% endif %}{% endblock %}

{% block content %}
<section class="row">
	<div class="col-md-12">
	<h1 class='header'>Dagens bokningar</h1>
	{% if today %}
	<div class="table-responsive" style="padding-bottom:5%;">
		<table class="table">
			<tr>
				<th>Bokningsnummer</th>
				<th>Förnamn</th>
				<th>Efternamn</th>
				<th>Telefon</th>
				<th>Paket</th>
				<th>Cyklar</th>
				<th>Rum</th>
				<th>Luncher</th>
			</tr>
			{% for booking in today %}
			<tr>
		    	<td><a href="{{ booking.get_absolute_url }}">{{ booking.booking }}</a></td>
		    	<td>{{ booking.guest.first_name }}</td>
		    	<td>{{ booking.guest.last_name }}</td>
		    	<td>{{ booking.guest.phone_number }}</td>
		    	<td>{% if booking.package %}{{ booking.package }}{% else %}Ej paket{% endif %}</td>
		    	<td>{% if booking.booked_bike.all %}{% for bike in booking.booked_bike.all %}{{ bike.bike }}{% endfor %}{% else %}Inga cyklar{% endif %}</td>
		    	<td>{% if booking.booked_rooms.all %}{% for room in booking.booked_rooms.all %}{{ room.room }}{% endfor %}{% else %}Inga rum{% endif %}</td>
		    	<td>{% if booking.booked_lunches.all %}{% for lunch in booking.booked_lunches.all %}{{ lunch.type }}{% endfor %}{% else %}Inga luncher{% endif %}</td>
		    </tr>
		    {% endfor %}
	    </table>
    </div>
    {% else %}
    <p> Inga bokningar idag! </p>
    {% endif %}
	</div>
	
	<div class="col-md-12" style="padding-bottom:5%;">
	<h1 class='header'>Bokningar imorgon</h1>
	{% if tomorrow %}
	<div class="table-responsive" >
		<table class="table table-hover">
			<tr>
				<th>Bokningsnummer</th>
				<th>Förnamn</th>
				<th>Efternamn</th>
				<th>Telefon</th>
				<th>Paket</th>
				<th>Cyklar</th>
				<th>Rum</th>
				<th>Luncher</th>
			</tr>
			{% for booking in tomorrow %}
			<tr>
		    	<td><a href="{{ booking.get_absolute_url }}">{{ booking.booking }}</a></td>
		    	<td>{{ booking.guest.first_name }}</td>
		    	<td>{{ booking.guest.last_name }}</td>
		    	<td>{{ booking.guest.phone_number }}</td>
		    	<td>{% if booking.package %}{{ booking.package }}{% else %}Ej paket{% endif %}</td>
		    	<td>{% if booking.booked_bike.all %}{% for bike in booking.booked_bike.all %}{{ bike.bike }} <br>{% endfor %}{% else %}Inga cyklar{% endif %}</td>
		    	<td>{% if booking.booked_rooms.all %}{% for room in booking.booked_rooms.all %}{{ room.room }} <br>{% endfor %}{% else %}Inga rum{% endif %}</td>
		    	<td>{% if booking.booked_lunches.all %}{% for lunch in booking.booked_lunches.all %}{{ lunch.type }} <br>{% endfor %}{% else %}Inga luncher{% endif %}</td>
		    </tr>
		    {% endfor %}
	    </table>
    </div>
    {% else %}
    <p> Inga bokningar imorgon! </p>
    {% endif %}
	</div>
	
	<div class="col-xs-12 col-md-12" style="padding-bottom:5%;">
	<h1 class='header'>Bokningar om 2 dagar</h1>
	{% if day_after_tomorrow %}
	<div class="table-responsive">
		<table class="table table-hover">
			<tr>
				<th>Bokningsnummer</th>
				<th>Förnamn</th>
				<th>Efternamn</th>
				<th>Telefon</th>
				<th>Paket</th>
				<th>Cyklar</th>
				<th>Rum</th>
				<th>Luncher</th>
			</tr>
			{% for booking in day_after_tomorrow %}
			<tr>
		    	<td><a href="{{ booking.get_absolute_url }}">{{ booking.booking }}</a><td>
		    	<td>{{ booking.guest.first_name }}</td>
		    	<td>{{ booking.guest.last_name }}</td>
		    	<td>{{ booking.guest.phone_number }}</td>
		    	<td>{% if booking.package %}{{ booking.package }}{% else %}Ej paket{% endif %}</td>
		    	<td>{% if booking.booked_bike.all %}{% for bike in booking.booked_bike.all %}{{ bike.bike }}{% endfor %}{% else %}Inga cyklar{% endif %}</td>
		    	<td>{% if booking.booked_rooms.all %}{% for room in booking.booked_rooms.all %}{{ room.room }}{% endfor %}{% else %}Inga rum{% endif %}</td>
		    	<td>{% if booking.booked_lunches.all %}{% for lunch in booking.booked_lunches.all %}{{ lunch.type }}{% endfor %}{% else %}Inga luncher{% endif %}</td>
		    </tr>
		    {% endfor %}
	    </table>
    </div>
    {% else %}
    <p> Inga bokningar om 2 dagar! </p>
    {% endif %}
	</div>
</section>
{% endblock %}

database/templates/bookings/viewfreebikes.html
{% extends "admin/app_index.html" %}
{% load i18n admin_modify %}
{% block extrahead %}{{ block.super }}
{% url jsi18n as jsi18nurl %}
<script src="{{ jsi18nurl}}" type="text/javascript"><!--mce:0--></script>  
{% endblock %}
{% block extrastyle %}{{ block.super }}
{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">  
     <a href="../../admin/">{% trans "Home" %}</a> ›
     {% trans 'Se alla bokningar' %}</div>
{% endif %}{% endblock %}

{% block content %}
	<h1 class='header'>Lediga cyklar</h1>
	{{ calendar }}

{% endblock %}