VisthusetAPI/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from VisthusetAPI.views import *
import database.views as booking


urlpatterns = [
    # Visthuset urls
    url(r'^$', IndexView, name="visthuset_index"),
    url(r'^meny/$', meny_view, name="meny"),
    url(r'^calendar/$', CalendarView.as_view(), name="calendar"),
    url(r'^events/', include('events.urls')),
    url(r'^about/$', about_view, name="about"),
    url(r'^contact/$', contact_view, name="contact"),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^uthyrning/$', UthyrningView.as_view(), name="uthyrning"),
    
    # API urls
    url(r'^api/$', APIIndexView.as_view(), name="api_index"),
    url(r'^admin/', admin.site.urls),
    url(r'^cleaning/', include('cleaning.urls')),
    url(r'^economy/', include('Economy.urls')),
    url(r'^booking/', include('database.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^admin/availablebike/$', booking.create_available_bikes, name='createbikes'),
]

database/urls.py
'''
Created on 16 okt. 2016

@author: Adrian
'''
from django.conf.urls import url
from . import views, calendars

app_name = "database"
urlpatterns = [
    # /bookings/
    url(r'^availablebike/$', views.create_available_bikes, name='createbikes'),
    url(r'^bookingcal/$', views.booking_calendar, name='bookingcalendar'),
    url(r'^viewbookings/$', views.view_bookings, name='bookings_today'),
    # /bookings/bookingNo/
    url(r'^calendar/$', calendars.calendar, name='eventcalendar'),
    url(r'^bikebooking/', views.customer_bike_booking_view, name='bike_booking'),
    url(r'^package/$', views.package_display, name='package_list'),
    url(r'^package/(?P<slug>[a-z]+)/', views.package_booking, name='package'),
    url(r'^(?P<pk>[0-9]+)/thanks/$', views.confirmation_view, name='confirmation'),
    #url(r'^(?P<booking>[0-9]+)/$', views.ViewBooking.as_view(), name='booking-detail')
    ]
#views.BikeBookingResponseView.as_view()    ]

docs/urls.py
'''
Created on 16 okt. 2016

@author: Adrian
'''
from django.conf.urls import url
from . import views

app_name = 'docs'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'Index'),
    url(r'^tutor/', views.tutor, name='Tutor'),
]

templates/Visthuset/about.html
{% extends '../visthuset_base.html'%}

{% block title %}<title>{{ page.title }}</title>{% endblock %}

{% block content %}
<section class="row">
		<div class="col-md-12">
		<h1>{{ page.headline }}</h1>
		{{ page.ingress | safe }}
	</div>
	{% for text in texts %}
	<div class="col-s-12 col-md-6">
		<h2>{{ text.headline }}</h2>
		{% if text.image %}
		<img class="img-responsive col-s-12 col-md-3" src="{{ text.image.url }}" alt="{{ text.image_alt }}">
		{% endif %}
		<p>{{ text.text | safe }}</p>
	</div>
	{% endfor %}
	<div class="col-s-12 col-md-4 col-lg-4">
		{% include '../social_snippets/facebook_box.html' %}
	</div>
</section>

<section class="row">
	<div class="col-s-12 col-md-12 col-lg-4">
		{% include '../social_snippets/tripadvisor_review.html' %}
	</div>
	
	<div class="col-s-12 col-md-12 col-lg-4"><!-- Instagram snippet --></div>
	
	<div class="col-s-12 col-md-12 col-lg-4"></div>
</section>

{% endblock %}

templates/Visthuset/calendar.html
{% extends '../visthuset_base.html'%}

{% block title %}<title>Cafe Visthuset - Evenemang</title>{% endblock %}

{% block content %}
<p> Här hamnar en kalender med våra evenemang</p>
{% endblock %}

templates/Visthuset/contact.html
{% extends '../visthuset_base.html'%}

{% block title %}<title>{{ page.title }}</title>{% endblock %}

{% block content %}
<section class="row" style="padding-bottom: 5%;">
	<div class="col-md-12">
		<h1>{{ page.headline }}</h1>
		{{ page.ingress | safe }}
	</div>
	{% for text in texts %}
	<div class="col-s-12 col-md-5 centered">
		<h2>{{ text.headline }}</h2>
		{% if text.image %}
		<img class="img-responsive col-s-12 col-md-3" src="{{ text.image.url }}" alt="{{ text.image_alt }}">
		{% endif %}
		<p>{{ text.text | safe }}</p>
	</div>
	{% endfor %}
	<div class="col-xs-12 col-md-6" align="center">
		{% include '../social_snippets/google_maps.html' %}
	</div>
</section>

{% endblock %}

templates/Visthuset/menu.html
{% extends '../visthuset_base.html' %}

{% block title %}<title>Cafe Visthuset - Vår meny</title>{% endblock %}

{% block content %}
<section class="row">
	<div class="col-md-12 col-md-12">
		<h1 > Café Visthusets meny! </h1>
		<p>
			På Café Visthuset i Töreboda serverar vi ett brett sortiment. Oavsett om du är, 
			fikasugen eller hungrig på något matigare, vill ha något svalkande kallt eller något 
			värmande, så har vi något för dig! Nedan kan du ta del av vårt utbud. 
		</p>
		
			<h2>Riktigt gott kaffe!</h3>
		<p> 
			<img class="img-responsive img-rounded" src="/static/img/coffeemaking.jpg" alt="Glass!" width="40%"/>
			
			Vi tycker det är viktigt med kvalitet i det vi serverar. Därför vill vi satsa på kärnan i caféet, 
			nämligen kaffet. Med olika bryggmetoder som på olika sätt lyfter kaffets 
			smaker vill vi dela med oss av en kaffeupplevelse och förmedla kaffekunskap. 
			Vi samarbetar med Johan och Nyström Kafferostare och Tehandlare. Kaffet är certiferat enligt 
			Fairtrade eller Direct Trade, vilket är Johan och Nyströms märkning där en stabil 
			handelsrelation och bra betalt är viktigt, precis som miljösatsningar. 
			Allt för att vi ska kunna servera Törebodas bästa kopp kaffe! 
			Om du vill ta med dig vår goda kaffeupplevelse hem så finns bönorna att köpa med sig hem i vår butik, 
			hela eller malda. <br>
			Läs mer om vårt kaffe på www.johanochnystrom.se och på www.lovecoffee.se
			
			</p>
		
	</div>

</section>			
	<hr>
<section class="row">
	<div class="col-md-12 col-md-12">
		<h2> Lunch</h2>
		<p>
			<img class="img-responsive img-rounded" src="/static/img/Grillad_macka.jpg" alt="Glass!" width="40%"/>
			
			I Café Visthusets sortiment finns förutom kaffe och sötsaker också matigare alternativ för den hungrige. 
			Vi jobbar med lokala varor av hög kvalitet, många av dessa varor hittar du dessutom i vår butik så att du kan 
			njuta av dem även hemma. 
		</p>
		<h3> Pajer </h3>
		<p>
			Prova våra fina pajer med sallad. Sortimentet varierar något från dag till dag men innehåller oftast Taco, Kyckling, Grekisk, och Lax & Spenat
		</p>
		<h3>Grillade mackor</h3>
	<p>
		Våra populära grillade smörgåsar med sallad är ytterligare ett lunchalternativ. Dessa gör vi på surdegsbröd, bakat i vårt egna, och med sallad från en odlare bara 2 km bort. 
	</p>
	<p>
		Våra varianter på smörgåsar är:<br>
		- Tomat, mild Gäseneost och basilika (Vegetarisk)<br>
		- Varmrökt klakonbröstfilé med färskost och ärtskott<br>
		- Kryddig lammkorv och mild Gäseneost<br>
		- Pulled Turkey med hemgjord barbequesås och vår picklade rödlök
		</p>
	</div>
</section>
<hr>
<section class="row">
	<div class="col-md-12 col-md-12">
			<h3> Sommarbrunch</h3>
		<p>
			På söndagar serverar vi vår somriga brunch med massor av fräscha godsaker såsom finpizza, färsk frukt, våfflor, 
			småtugg och såklart en liten sötsak till! 
		</p>
		<p>
			Helt enkelt allt som behövs för sköna söndagsmorgnar!
		</p>
			<p>
			Brunchen öppen söndagar kl. 10-14
		</p>
		<p>
			Vuxen: 145 kr <br>
				Barn: 75 kr 
		</p>
	</div>
</section>
<hr>
<section class="row">
	<div class="col-md-12 col-md-12">
			<h3>Smörgåsar</h3>
		<p>
			<img class="img-responsive img-rounded" src="/static/img/api/glass.jpg" alt="Glass!" width="40%"/>
			Vi erbjuder även ett antal olika smörgåsar. Till dessa använder vi surdegsbröd eller brödkakor från 
			vårt eget bageri samt pålägg från lokala producenter. 
		</p>
			<p>
			I regel kan vi erbjuda följande varianter:<br>
		
			- Köttbullemacka - En klassiker! <br>
				- Räksmörgås med ägg och skagenröra <br>
			- Ostsmörgås <br>
			- Ost- och Skinksmörgås
			</p>
	</div>
</section>
<hr>
<section class="row">
	<div class="col-md-12 col-md-12">
		<h3>Fika</h3>
		<h4> Får det lov att vara något sött till kaffet?</h4> 
		<p>
			<img class="img-responsive img-rounded" src="/static/img/Kaka.jpg" alt="Glass!" width="40%"/>
			Vårt utbud varierar under säsongen, 
			men några klassiker som vi utmed allt annat nästan alltid har att erbjuda är:
		</p>
		<p>
			- hembakta Chokladbollar med pärlsocker eller kokos <br>
			- hembakt morotskaka <br>
			- hembakt kladdkaka
			<p>
			I regel kan vi alltid erbjuda några raw food alternativ också, som vi bakar själva i vårt eget kök. 
			Vi kan ofta erbjuda sorter som exempelvis:
		</p>
		<p>
			- Key Lime Pie <br>
			- Choklad och Hallonkaka
		</p>
		<p>
			Den lokala glassmanufakturen "Klings" levrerar både lösglass och styckglass till oss. 
			Välj mellan ett brett urval av klassiska och nya smaker!
		</p>
		<p>
			En klassiker och mycket populärt bland både barn och vuxna är våra våfflor, 
			som vi gräddar färsk på beställning. Våfflorna serveras med lokalproducerad sylt och en klick grädde. 
		</p>
		<p>
			På riktigt varma sommardagar kan det vara gott med en kall dricka. Vi erbjuder därför även cider, 
			isté, must, saft, läsk och lättöl från flera olika lokala producenter.
		</p>
	</div>
</section>  
{% endblock %}

templates/Visthuset/meny.html
{% extends '../visthuset_base.html' %}
{% load static %}
{% block title %}<title>{{ page.title }}</title>{% endblock %}

{% block content %}
<section class="row">
	<div class="col-md-12">
		<h1>{{ page.headline }}</h1>
		{{ page.ingress | safe }}
	</div>
	{% for text in texts %}
	<div class="col-md-12">
		<h2 class="col-md-12">{{ text.headline }}</h2>
		{% if text.image %}
		<img class="img-responsive col-s-12 col-md-3" src="{{ text.image.url }}" alt="{{ text.image_alt }}">
		<div class="col-s-12 col-md-9 pull-right">
			{{ text.text | safe }}
		</div>
		{% else %}	
		<div class="col-m-12">
			{{ text.text | safe }}
		</div>
		{% endif %}	
	</div>
	{% endfor %}
	
</section>
{% endblock %}
<!-- {% static '/img/uploads/coffeemaking.jpg' %}
<section class="row">
	<div class="col-md-12 col-md-12">
		<h1 > Café Visthusets meny! </h1>
		<p>
			På Café Visthuset i Töreboda serverar vi ett brett sortiment. Oavsett om du är, 
			fikasugen eller hungrig på något matigare, vill ha något svalkande kallt eller något 
			värmande, så har vi något för dig! Nedan kan du ta del av vårt utbud. 
		</p>
		
			<h2>Riktigt gott kaffe!</h3>
		<p> 
			<img class="img-responsive img-rounded" src="/static/img/coffeemaking.jpg" alt="Glass!" width="40%"/>
			
			Vi tycker det är viktigt med kvalitet i det vi serverar. Därför vill vi satsa på kärnan i caféet, 
			nämligen kaffet. Med olika bryggmetoder som på olika sätt lyfter kaffets 
			smaker vill vi dela med oss av en kaffeupplevelse och förmedla kaffekunskap. 
			Vi samarbetar med Johan och Nyström Kafferostare och Tehandlare. Kaffet är certiferat enligt 
			Fairtrade eller Direct Trade, vilket är Johan och Nyströms märkning där en stabil 
			handelsrelation och bra betalt är viktigt, precis som miljösatsningar. 
			Allt för att vi ska kunna servera Törebodas bästa kopp kaffe! 
			Om du vill ta med dig vår goda kaffeupplevelse hem så finns bönorna att köpa med sig hem i vår butik, 
			hela eller malda. <br>
			Läs mer om vårt kaffe på www.johanochnystrom.se och på www.lovecoffee.se
			
			</p>
		
	</div>

</section>			
	<hr>
<section class="row">
	<div class="col-md-12 col-md-12">
		<h2> Lunch</h2>
		<p>
			<img class="img-responsive img-rounded" src="/static/img/Grillad_macka.jpg" alt="Glass!" width="40%"/>
			
			I Café Visthusets sortiment finns förutom kaffe och sötsaker också matigare alternativ för den hungrige. 
			Vi jobbar med lokala varor av hög kvalitet, många av dessa varor hittar du dessutom i vår butik så att du kan 
			njuta av dem även hemma. 
		</p>
		<h3> Pajer </h3>
		<p>
			Prova våra fina pajer med sallad. Sortimentet varierar något från dag till dag men innehåller oftast Taco, Kyckling, Grekisk, och Lax & Spenat
		</p>
		<h3>Grillade mackor</h3>
	<p>
		Våra populära grillade smörgåsar med sallad är ytterligare ett lunchalternativ. Dessa gör vi på surdegsbröd, bakat i vårt egna bageri, och med sallad från en odlare bara 2 km bort. 
	</p>
	<p>
		Våra varianter på smörgåsar är:<br>
		- Tomat, mild Gäseneost och basilika (Vegetarisk)<br>
		- Varmrökt klakonbröstfilé med färskost och ärtskott<br>
		- Kryddig lammkorv och mild Gäseneost<br>
		- Pulled Turkey med hemgjord barbequesås och vår picklade rödlök
		</p>
	</div>
</section>
<hr>
<section class="row">
	<div class="col-md-12 col-md-12">
			<h3> Sommarbrunch</h3>
		<p>
			På söndagar serverar vi vår somriga brunch med massor av fräscha godsaker såsom finpizza, färsk frukt, våfflor, 
			småtugg och såklart en liten sötsak till! 
		</p>
		<p>
			Helt enkelt allt som behövs för sköna söndagsmorgnar!
		</p>
			<p>
			Brunchen öppen söndagar kl. 10-14
		</p>
		<p>
			Vuxen: 145 kr <br>
				Barn: 75 kr 
		</p>
	</div>
</section>
<hr>
<section class="row">
	<div class="col-md-12 col-md-12">
			<h3>Smörgåsar</h3>
		<p>
			<img class="img-responsive img-rounded" src="/static/img/api/glass.jpg" alt="Glass!" width="40%"/>
			Vi erbjuder även ett antal olika smörgåsar. Till dessa använder vi surdegsbröd eller brödkakor från 
			vårt eget bageri samt pålägg från lokala producenter. 
		</p>
			<p>
			I regel kan vi erbjuda följande varianter:<br>
		
			- Köttbullemacka - En klassiker! <br>
				- Räksmörgås med ägg och skagenröra <br>
			- Ostsmörgås <br>
			- Ost- och Skinksmörgås
			</p>
	</div>
</section>
<hr>
<section class="row">
	<div class="col-md-12 col-md-12">
		<h3>Fika</h3>
		<h4> Får det lov att vara något sött till kaffet?</h4> 
		<p>
			<img class="img-responsive img-rounded" src="/static/img/Kaka.jpg" alt="Glass!" width="40%"/>
			Vårt utbud varierar under säsongen, 
			men några klassiker som vi utmed allt annat nästan alltid har att erbjuda är:
		</p>
		<p>
			- hembakta Chokladbollar med pärlsocker eller kokos <br>
			- hembakt morotskaka <br>
			- hembakt kladdkaka
			<p>
			I regel kan vi alltid erbjuda några raw food alternativ också, som vi bakar själva i vårt eget kök. 
			Vi kan ofta erbjuda sorter som exempelvis:
		</p>
		<p>
			- Key Lime Pie <br>
			- Choklad och Hallonkaka
		</p>
		<p>
			Den lokala glassmanufakturen "Klings" levrerar både lösglass och styckglass till oss. 
			Välj mellan ett brett urval av klassiska och nya smaker!
		</p>
		<p>
			En klassiker och mycket populärt bland både barn och vuxna är våra våfflor, 
			som vi gräddar färsk på beställning. Våfflorna serveras med lokalproducerad sylt och en klick grädde. 
		</p>
		<p>
			På riktigt varma sommardagar kan det vara gott med en kall dricka. Vi erbjuder därför även cider, 
			isté, must, saft, läsk och lättöl från flera olika lokala producenter.
		</p>
	</div>
</section>  -->

templates/Visthuset/uthyrning.html
{% extends 'visthuset_base.html' %}
{% load static %}
{% block titel %}Cykla längs Göta kanal!{% endblock %}
{% block content %}
	<section class="row">
		<a href="{% url 'database:bike_booking' %}">
			<div class="col-xs-12 col-md-4 img-hover">
				<img class="img-responsive img-rounded" src="{% static 'img/cyklar.jpg' %}" alt="Kolla in vår dokumentation!" width="100%"/>
				<h3 top="100%">Hyr cykel!</h3>
			</div>
		</a>
		<a href="{% url 'database:package_list' %}">
			<div class="col-xs-12 col-md-4 img-hover">
    			<img class="img-responsive img-rounded" src="{% static 'img/cykel_paket.jpeg' %}" alt="Logga in!" width="100%"/>
				<h3>Våra cykelpaket</h3><br>
			</div>
		</a>
	</section>
{% endblock %}