VisthusetAPI/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from VisthusetAPI.views import *
import database.views as booking


urlpatterns = [
    # Visthuset urls
    url(r'^$', IndexView, name="visthuset_index"),
    url(r'^meny/$', meny_view, name="meny"),
    url(r'^calendar/$', CalendarView.as_view(), name="calendar"),
    url(r'^events/', include('events.urls')),
    url(r'^about/$', about_view, name="about"),
    url(r'^contact/$', contact_view, name="contact"),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^uthyrning/$', UthyrningView.as_view(), name="uthyrning"),
    
    # API urls
    url(r'^api/$', APIIndexView.as_view(), name="api_index"),
    url(r'^admin/', admin.site.urls),
    url(r'^cleaning/', include('cleaning.urls')),
    url(r'^economy/', include('Economy.urls')),
    url(r'^booking/', include('database.urls')),
    url(r'^docs/', include('docs.urls')),
    url(r'^admin/availablebike/$', booking.create_available_bikes, name='createbikes'),
]

docs/urls.py
'''
Created on 16 okt. 2016

@author: Adrian
'''
from django.conf.urls import url
from . import views

app_name = 'docs'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'Index'),
    url(r'^tutor/', views.tutor, name='Tutor'),
]

events/urls.py
from django.conf.urls import url
from . import views

app_name = 'events'
urlpatterns = [
    url(r'^$', views.event, name="event"),
    ]

templates/APIindex.html
{% extends 'visthuset_base.html' %}
{% load static %}

{% block title %}<title>Välkommen till Café Visthusets API</title>{% endblock %}

{% block content %}
	<section class="row">
		<div class="col-md-12">
			<h2>Vad vill du göra?</h2>
		    <p> Sidan är för tillfället under konstruktion. </p>
		</div>
		<div class="col-md-12 col-md-6 img-hover">
    		<a href="/admin/">
	    	    <img class="img-responsive img-rounded" src="{% static '/img/api/logga_in.jpg' %}" alt="Logga in!"/>
	    	    <h3>Logga in!</h3><br>
  	  		</a>
  	  	</div>
  	  	<div class="col-md-12 col-md-6 img-hover">
  	  		<a href="/docs/">
  		    	<img class="img-responsive img-rounded" src="{% static '/img/api/glass.jpg' %}" alt="Kolla in vår dokumentation!" />
    		  	<h3>Kolla in vår dokumentation!</h3>
    		</a>
    	</div>
    </section>
{% endblock %}

templates/banner.html
{% load static %}
{% load l10n %}

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	<!-- Indicators -->
	<ol class="carousel-indicators">
		<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		<li data-target="#carousel-example-generic" data-slide-to="1"></li>
		<li data-target="#carousel-example-generic" data-slide-to="2"></li>
	</ol>
					
	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
				
		<div class="item active">
			<a href="{% url 'visthuset_index' %}">
			<img src="{% static '/img/banner_ute_musik.jpg' %}" alt="...">
			<div class="carousel-caption">
				<h1>Café Visthuset</h1>
				<h3>En lummig mötesplats vid Göta kanal</h3>
			</div>
			</a>
		</div>
		<div class="item">
			<a href="{% url 'meny' %}">
				<img src="{% static 'img/Glassbild3.jpg' %}" alt="...">
				<div class="carousel-caption">
					<h1>Café Visthuset</h1>
				    <h3>Glass vid Göta kanal!</h3>
				</div>
				</a>
		</div>
					<div class="item">
						<a href="{% url 'uthyrning' %}">
						    <img src="{% static 'img/unspecified.jpeg' %}" alt="...">
						    <div class="carousel-caption">
						        <div style="margin-top: 5%;" >
				          			<h1>Café Visthuset</h1>
				          			<h3>Hyr en cykel vid Göta kanal!</h3>
				        		</div>
							</div>
						</a>
					</div>			    
				</div>
					
	<!-- Controls -->
	<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
		<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>

templates/failed.html
{% extends 'visthuset_base.html' %}

{% block title %}Något gick fel..{% endblock %}

{% block content %}
<div class="row">
	<h1>Ojdå! Det verkar som att något tekniskt gått snett...</h1>
	<p>Ring eller mejla oss gärna istället så kan vi säkert lösa problemet.<br>
	Telefon: +46 (0)506 - 77 75 50<br>
	Epost: <a href="mailto:info@cafevisthuset.se">info@cafevisthuset.se</a>
	</p>
</div>
{% endblock %}

templates/footer.html
{% load static %}
<footer class="row">
	<div class="col-md-12 centered" style="margin-top: 3%;">
		<div class="col-s-12 col-md-4 centered">
		{% include './social_snippets/facebook_like.html' %}
		</div>

		<div class="col-s-12 col-md-2 centered">
		{% include './social_snippets/tripadvisor_footer.html' %}
		</div>
	</div>
	<div class="col-md-12 col-md-3" style="margin-top: 2%;" >
    	<h3>Kontakta oss!</h3>
      	<adress>Café Visthuset<br>
	    Kanalvägen 2, Töreboda<br></adress>
    	<a href="tel:+46506777550">0506 - 77 75 50</a><br>
        <a href="mailto:info@cafevisthuset.se">info@cafevisthuset.se</a><br><br>
      	<a href="{% url 'visthuset_index' %}">www.cafevisthuset.se</a><br>
      	<a href="http://www.cyklagotakanal.se">www.cyklagotakanal.se</a>
    </div>
    <div class="col-md-12 col-md-3">
    	<a href="{% url 'api_index' %}">
       		<img class="img-responsive img-rounded" style="margin-top: 14%; height: 170px;" src="{% static 'img/footer/gk_officiell_partner.jpg' %}"/>
        </a>
    </div>
    <div class="col-md-12 col-md-3">
    	<a href="/api/">
        	<img class="img-responsive img-rounded" style="margin-top: 22%; background: white; height: 130px;" src="{% static 'img/footer/vastsverige_svensk.jpg' %}" />
        </a>
    </div>
    <div class="col-md-12 col-md-3" style="margin-top: 4%;" >            
    	<h3>Öppettider</h3>
        Vi har öppet juni - augusti samt helger i maj och september.
            
        <h3>Samarbeta med oss!</h3>
        <a href="{% url 'api_index' %}">
     	<p>API</p>
    	</a>
    </div>
 </footer>

templates/index.html
{% extends 'visthuset_base.html' %}
{% load static %}
{% load l10n %}

{% block title %}<title>Välkommen till Cafe Visthuset!</title>{% endblock %}
{% block header %}
	<header class="row">
			{% if page.static_banner %}
			<div class="item">
				<img src="{{ page.banner.image.url }}" alt="{{ page.banner.imagealt }}">
				<div class="carousel-caption">
					<h1>Café Visthuset</h1>
				    <h3>Glass vid Göta kanal!</h3>
				</div>
			</div>
			{% else %}
				{% include 'banner.html' %}
			{% endif %}
			<div class="row">
	        	<div class="col-md-12 col-md-12"> 
	        		
	        	</div>
	        	
	    	</div>
  		{% include 'navbar.html' %}
  	</header>
{% endblock %}

{% block content %}
      		<section class="row">
      			<div class="col-s-10 col-md-12">
      			<h1 class="text-center text-info">Välkommen till Cafe Visthuset!</h1>
      			{% for link in links %}
      			{% endfor %}
      			<a href="{% url 'meny' %}">
					<div class="col-xs-12 col-md-4 img-hover">
						<img class="img-responsive img-rounded" src="{% static 'img/coffeemaking.jpg' %}" alt="Kolla in vår dokumentation!" width="100%"/>
	 				<h3 top="100%">Här är vår meny!</h3>
					</div>
				</a>
				<a href="{% url 'uthyrning' %}">
				<div class="col-xs-12 col-md-4 img-hover">
    				<img class="img-responsive img-rounded" src="{% static 'img/cyklar.jpg' %}" alt="Logga in!" width="100%"/>
					<h3>Visthusets cykeluthyrning!</h3><br>
				</div>
				</a>
				<a href="{% url 'contact' %}">
					<div class="col-xs-12 col-md-4 img-hover" height="100%">
						<img class="img-responsive img-rounded" src="{% static 'img/contact.jpg' %}" alt="Kolla in vår dokumentation!" width="100%"/>
	 					<h3 top="100%">Kontakta oss!</h3>
					</div>
				</a>
				</div>
			{% if events %}	
			<h1 class="col-sm-12 text-center text-info">Det här händer på Café Visthuset</h1>
			<div class="row">
				{% for event in events %}
				<a href="{% url 'events:event' %}">
					<div class="col-sm-12 col-md-4 img-hover">
						<div class='imageholder'>
				    	<img class="img-responsive img-rounded" src="{{ event.image.url }}" alt="{{ event.imageAlt }}" width="100%"/>
						<div class='watermark'>
							{{event.start_date|date:"d"}}<hr>{{ event.start_date|date:"M"|localize }}</div>
					</div>
					<h3 top="100%">{{ event.title }}</h3>
						<p>{{ event.description | safe}}</p><br>
					</div>
				</a>
				
			{% endfor %}
			</div>
			{% endif %}
		</section>
{% endblock %}

templates/javascripts.html
{% load compress %}
{% load static %}
{% compress js %}
<script type="text/javascript" src="{% static 'js/ckeditor.js' %}"></script>
<script type="text/javascript" src="{% static 'js/ckeditor-init.js' %}"></script>

<!-- Tripadvisor -->
<!--  <script src="https://www.jscache.com/wejs?wtype=socialButtonBubbles&amp;uniq=818&amp;locationId=6985659&amp;color=green&amp;size=rect&amp;lang=sv&amp;display_version=2"></script> -->
<script src="https://www.jscache.com/wejs?wtype=cdswritereviewlg&amp;uniq=525&amp;locationId=6985659&amp;lang=sv&amp;lang=sv&amp;display_version=2"></script>
<script src="https://www.jscache.com/wejs?wtype=restaurantWidgetGreen&amp;uniq=324&amp;locationId=6985659&amp;icon=cupOfCoffee&amp;lang=sv&amp;display_version=2"></script>

<!-- Browser sync -->
<script id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.js?v=2.18.6'><\/script>".replace("HOST", location.hostname));
//]]></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endcompress %}

templates/navbar.html
<div class="row">
	<nav class="navbar navbar-default">
    	<div>
        	<div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span> 
                </button>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
            	<ul class="nav navbar-nav">
                  <li><a href="{% url 'visthuset_index' %}">Visthuset</a></li>
                  <li><a href="{% url 'meny' %}">Meny</a></li>
                  <li><a href="{% url 'events:event' %}">Evenemang</a></li> 
                  <li><a href="{% url 'uthyrning' %}">Cykeluthyrning</a></li>
                  <li><a href="{% url 'about' %}">Om oss</a></li>
                  <li><a href="{% url 'contact' %}">Kontakta oss!</a></li>
                </ul>
            </div>
        </div>
	</nav>
</div>

templates/stylesheets.html
{% load compress %}
{% load static %}
{% compress css %}
<!-- Base styles -->
<link rel="stylesheet" type="text/css" href="{% static 'css/Visthuset/visthuset_base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/Visthuset/navbar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/Visthuset/footer.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/Visthuset/forms.css' %}">
<!-- Visthuset styles -->


<!-- Bootstrap 3-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
{% endcompress %}

templates/visthuset_base.html
{% load static %}
{% load l10n %}
<!DOCTYPE html>
<html lang="sv">
	<head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	{% block title %}{% endblock %}
    	{% include 'stylesheets.html' %}
    </head>
	<body class="container-fluid">
		{% block header %}{% endblock %}
    	<main>
    	{% block content %}
		  {% endblock %}
    	</main>

    </body>
		{% include 'javascripts.html' %}
		{% block javascripts %}{% endblock %}
		{% include 'footer.html' %}
</html>